### ISSUE TITLE
api出问题了吗

### ISSUE THREAD

**Issue by ghost** [yuantuo666/baiduwp-bot#4]
Warning: mysqli_connect(): (HY000/1045): Access denied for user 'core'@'localhost' (using password: YES) in /www/wwwroot/imwcr.cn/api/bdwp-core/api.php on line 65
改了下想用其它方式获取链接，让QQ的bot也能用，但是获取的时候出现了这个错误

然后试了试https://imwcr.cn/api/bdwp-core/可不可用，多次确认参数，还是说传参错误

**Comment by yuantuo666** [comment]
😥 之前的服务器到期了
更换服务器忘了配置数据库

**Comment by yuantuo666** [comment]
已尝试修复，请重新尝试

**Comment by ghost** [comment]
> 已尝试修复，请重新尝试

非常感谢，已经可以正常获取了！
